### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by tr1s** [manzinello/gatsby-plugin-mailgo#1]
I installed the package, tried with and without dark mode, nothing. I click the `mailto:` link and nothing happens. No errors in the console either. Tried with Firefox, Chrome, Safari.

The moment I remove mailgo from the gatsby-config my normal `matilto:` links work again.

Anyone else?

**Comment by manzinello** [comment]
Here I am!

I really want to understand what's happening here. Just to understand better: are you passing a configuration object to mailgo in `gatsby-config`? To understand better the problem (possibly a bug) I have built now (in a record time!) a repository with a Gatsby (starter default) and mailgo (with configuration object, dark mode in particular). Here the repository: https://github.com/manzinello/gatsby-mailgo-example and here the website already deployed: https://gatsby-mailgo-example.netlify.app/, is this something that can be useful also in the future. Everything seems to be fine here, can you help me to check what's happening with your installation of **gatsby-plugin-mailgo**? Maybe there is something wrong with HTML visibility o elements or CSS? Is there the element with `id="mailgo"` in the DOM?

Well, is a public repository the project you are working on?

Thank you, I will try to make my best to solve the problem, if it is something wrong in mailgo JS then we will return in manzinello/mailgo.

**Comment by manzinello** [comment]
Hi @tr1s, any update about this? I leave you also the `gatsby-config` I am using in `gatsby-mailgo-example` https://github.com/manzinello/gatsby-mailgo-example/blob/master/gatsby-config.js. Obviously you can use it without configuration and just adding the string `gatsby-plugin-mailgo`. Please, let me know.

**Comment by AlexFernando** [comment]
Hi @manzinello, first of all, thanks for taking the time to do this cool plugin, unfortunately I have an error while trying to execute 'gatsby build' for deployment purposes. The error  --> "window" is not available during server side rendering, WebpackError: ReferenceError: window is not defined.  Did you get this error while trying to deploy your example? I understand that I have to define window somewhere but,  Where exactly? or , how should manage it?   Thanks in advance
![err1_gatsby_mailgo](https://user-images.githubusercontent.com/9219348/93419694-096e5100-f89d-11ea-9484-62ab514d36be.png)
![err2_gatsby_mailgo](https://user-images.githubusercontent.com/9219348/93419696-0b381480-f89d-11ea-9d2a-ee0e1018185f.png)

**Comment by tr1s** [comment]
> Hi @tr1s, any update about this? I leave you also the `gatsby-config` I am using in `gatsby-mailgo-example` https://github.com/manzinello/gatsby-mailgo-example/blob/master/gatsby-config.js. Obviously you can use it without configuration and just adding the string `gatsby-plugin-mailgo`. Please, let me know.

Hey @manzinello, [I made a PR](https://github.com/tr1s/tris-portfolio-blog/tree/mailgo) with the mailgo updates, maybe you can see what I'm doing wrong?

Thanks, let me know! As far as I know it looks the same as yours.

**Comment by manzinello** [comment]
Hi @AlexFernando, it's a really good point. I have worked on SSR in mailgo in [NextJS](https://mailgo.dev/docs/nextjs) section of the docs. I don't know if it can be useful for you (in fact it is a really generic guide). Thank you for your message, I have to work to rename the section from "NextJS" to "SSR" in general and focus also on Gatsby SSR. The point is that `mailgo()` must be called with `window` defined, it's been explained also [here](https://mailgo.dev/docs/installation#npm--yarn). Please can you tell me if the links I have provided are useful? I obviously will work on a better docs also for Gatsby SSR, really thank you.

**Comment by manzinello** [comment]
Hi @tr1s, I've cloned your repo (in the `mailgo` branch) and found what's happening! There's an error in `mailto` link format. I attach you what I have found in `index.jsx` file:

<img width="406" alt="Screenshot 2020-09-17 at 08 23 20" src="https://user-images.githubusercontent.com/5347132/93428176-4a775d00-f8bf-11ea-8794-62e479af5242.png">

The problem here is that mailgo before start fires a `validateEmail()` function that fails! So no modal is shown. (you can also disable the [validateEmail through config](https://mailgo.dev/docs/configuration#validateemail)).

If you change the `mailto:` address with a correct one mailgo correctly shows (with also the dark mode that you have specified in `gatsby-config`).

<img width="826" alt="Screenshot 2020-09-17 at 08 23 38" src="https://user-images.githubusercontent.com/5347132/93428302-798dce80-f8bf-11ea-9e33-93069cf43834.png">

I think that the problem is this one!

Just a thing: at first I have seen the wrong branch of you repo (I was seeing the `master` branch), I just want to report you this about **mailgo**. After the commit https://github.com/tr1s/tris-portfolio-blog/commit/fd3c7d284e70b9721d1a6215de5698fc5d9f481e in `Browse files` it seems that `gatsby-plugin-mailgo` is not present in `gatsby-config`, you can see it here: https://github.com/tr1s/tris-portfolio-blog/blob/fd3c7d284e70b9721d1a6215de5698fc5d9f481e/gatsby-config.js. I don't know if you have just tested this in localhost and then not commit the updated file.
However, in the mailgo branch with the fix of the `mailto` format everything works correctly.

Please, let me know if everything is ok after this comment. If everything is ok I will close this issue!

**Comment by manzinello** [comment]
@tr1s let me know if everything is ok after this comment. If everything works I will close the issue to open a new one with the question about `window` from @AlexFernando, that is a different question.

**Comment by tr1s** [comment]
Ahhhh yes yes. Makes sense. My broken `mailto:` format with the `https` was working fine regardless so I hadn't even noticed I had it in the wrong format.

Thanks!

**Comment by manzinello** [comment]
Perfect @tr1s!

@AlexFernando I've just opened this issue for the problem of window. I think that it is already solved as a problem, but I have in any case to update the docs to be more clear about it. https://github.com/manzinello/mailgo/issues/84

**Comment by manzinello** [comment]
Hi @AlexFernando, sorry but I'm studying the problem of `window`, but have you followed the guide of `gatsby-plugin-mailgo` specified here https://www.gatsbyjs.com/plugins/gatsby-plugin-mailgo? Can you give me the repo of your project? Thank you.
